### ISSUE TITLE
    uint256 public override totalSupply;   

### ISSUE THREAD

**Issue by githublister** [AmazingAng/WTFSolidity#145]
不太明白 
一个变量为什么能重截函数

**Comment by AmazingAng** [comment]
public状态变量可以自动创建一个同名的`getter`函数，能override继承的父合约的同名函数。比如IERC721Metadata中的`totalSupply`

**Comment by githublister** [comment]
谢谢！这个知识点好细节。

**Comment by githublister** [comment]
问题: 既然是新变量为什么 我要用一个重名的totalSupply 去overrite  。我弄一个新的变量  new_totalSupply  这样不是更好么？

**Comment by AmazingAng** [comment]
要实现接口定义的totalSupply函数，你用什么方式实现都可以。
