### ISSUE TITLE
第22讲，因为顺序调换，文中链接问题

### ISSUE THREAD

**Issue by SBFPGLN** [AmazingAng/WTFSolidity#148]

**Comment by AmazingAng** [comment]
第几行顺序不对？

**Comment by SBFPGLN** [comment]
> 第几行顺序不对？

正文第6行放置的链接：“第19讲：调用其他合约](https://github.com/AmazingAng/WTFSolidity/tree/main/19_CallContract)”

**Comment by AmazingAng** [comment]
是mirror还是github? github上面的好像没问题

**Comment by SBFPGLN** [comment]
> 是mirror还是github? github上面的好像没问题

mirror上
