### ISSUE TITLE
第38讲细节

### ISSUE THREAD

**Issue by cnukaus** [AmazingAng/WTFSolidity#159]
十分感谢分享！
第38讲，如果按例子顺序执行，那么用`NFTSwap`合约的`update()`函数，将NFT价格更新为77 `wei`， 后面的 购买 1gwei就不够了。。要么把购买的价格设为78gwei,这样还能顺带测试下找零？

**Comment by AmazingAng** [comment]
感谢 
@EasyChris 可以修改下不？

**Comment by EasyChris** [comment]
可以的，我晚点提一个pr

**Comment by EasyChris** [comment]
> 十分感谢分享！ 第38讲，如果按例子顺序执行，那么用`NFTSwap`合约的`update()`函数，将NFT价格更新为77 `wei`， 后面的 购买 1gwei就不够了。。要么把购买的价格设为78gwei,这样还能顺带测试下找零？

价格更新为77`wei`,任意一个账号购买的价格应该也是77`wei` 77`wei`是一个很小的数据，这个应该不影响你后续的购买吧？

你是不是执行了下架之后NFT，之后再执行购买，导致NFT不能正常购买？

**Comment by EasyChris** [comment]
修正了之前文章中的歧义，调整了上下架的tokenId

https://github.com/AmazingAng/WTFSolidity/pull/162
