### ISSUE TITLE
文档增加代码高亮

### ISSUE THREAD

**Issue by zhenfeng-zhu** [AmazingAng/WTFSolidity#171]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/6822558/185528091-df397342-f080-449f-ba5f-6460d7a1c28c.png">

这里有一些没有换行，同时希望能够引入高亮的功能。

**Comment by AmazingAng** [comment]
![Screenshot_2022-08-19-10-30-56-616_com.github.android.jpg](https://user-images.githubusercontent.com/14728591/185530024-65ad5a38-4d21-4e2b-bbad-adcffa2e0cbb.jpg)

Github上的最新版是有高亮的，mirror上的还没换，因为编辑起来比较费劲，估计这几天慢慢换。

**Comment by zhenfeng-zhu** [comment]
嗯，我是在官网看到的，是没有高亮的

**Comment by zhenfeng-zhu** [comment]
https://wtf.academy/docs/HelloWeb3/

**Comment by AmazingAng** [comment]
> https://wtf.academy/docs/HelloWeb3/

好的 我更新下 感谢

**Comment by AmazingAng** [comment]
已增加❤️
