### ISSUE TITLE
21讲建议细化合约名的描述

### ISSUE THREAD

**Issue by beihaili** [AmazingAng/WTFSolidity#179]
原文：我们可以利用合约的地址和合约代码（或接口）来创建合约的引用：_Name(_Address)，其中_Name是合约名，_Address是合约地址。然后用合约的引用来调用它的函数：_Name(_Address).f()，其中f()是要调用的函数。

读的时候没读懂合约代码（或接口）是如何在调用时使用的。所以建议细化一下描述修改为：

我们可以利用合约的地址和合约代码（或接口）来创建合约的引用：_Name(_Address)，其中_Name是合约名，应与合约代码（或借口）中标注的合约名保持一致，_Address是合约地址。然后用合约的引用来调用它的函数：_Name(_Address).f()，其中f()是要调用的函数。

**Comment by AmazingAng** [comment]
好建议，你提个pr吧

**Comment by AmazingAng** [comment]
solved in #181
