### ISSUE TITLE
2. 数值类型 中2.整型 的代码有错误

### ISSUE THREAD

**Issue by eemsyw** [AmazingAng/WTFSolidity#184]
`uint256 public _number1 = _number + 1; // +，-，*，/`
应该是
`uint256 public _number1 = _number1 + 1; // +，-，*，/`

**Comment by AmazingAng** [comment]
没错啊，就是_number

**Comment by eemsyw** [comment]
> 没错啊，就是_number

抱歉，我没有认清文章含义
