### ISSUE TITLE
第三十四讲 ERC721合约 转账函数_transfer()被授权人错误

### ISSUE THREAD

**Issue by pacinoxiey** [AmazingAng/WTFSolidity#213]
学到721合约发现_transfer()函数有个参数似乎填错.下面是原始代码:
![1663476099932](https://user-images.githubusercontent.com/25141686/190886113-9404d67e-6764-4695-8dff-62407ea89ad2.jpg)
_approve函数的第二个参数address(0)应该是被授权地址'to'.

**Comment by AmazingAng** [comment]
这个操作是清空授权，不是错误。

**Comment by pacinoxiey** [comment]
理解了, 谢谢
