### ISSUE TITLE
第十三章，代码存在循环引用？

### ISSUE THREAD

**Issue by scqsu** [AmazingAng/WTFSolidity#214]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/10421790/190975275-9d76df1d-2e3d-4cbf-8046-bfcabffd70d1.png">

**Comment by AmazingAng** [comment]
这个应该是后补的代码。
@lilyang1989 看一下这个

**Comment by AmazingAng** [comment]
的确有循环引用，已修复。
https://github.com/AmazingAng/WTFSolidity/commit/0ce55d1daf3babf535a91ac5eca22c00d1758d6c

**Comment by lilyang1989** [comment]
的确存在这个问题。感谢指出，一会我再完善一下。

**Comment by lilyang1989** [comment]
已对错误的地方作出更正，感谢
