### ISSUE TITLE
状态变量用override修饰是什么意思

### ISSUE THREAD

**Issue by junhzhan** [AmazingAng/WTFSolidity#217]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/5052478/191442575-395c8cae-9c90-458c-8487-fc478ffdf699.png">
在31讲ERC20合约实现中，有几个状态变量用了override关键字修饰（如上图所示） ，这个修饰是起到什么作用

**Comment by 0x0918** [comment]
是这样子的，我是这样人为的，ERC20实现接口IERC20时候，在接口中，所有函数默认自动加上virtual：
` function allowance(address owner, address spender) external view returns (uint256);`
`function totalSupply() external view returns (uint256);`
后续实现的时候所用到相应函数必须加上override才能重写，而且external ===> public，自动生成同名函数`getter`

**Comment by AmazingAng** [comment]
@0x0918 解释的完全正确，我也把相应部分更新在了WTF Solidity第13讲和第31将中。
