### ISSUE TITLE
第 46 讲，代码中 Caller Contract 直接用方法名 Bytes4 字符串作为参数，无法调用成功，需要修改一下

### ISSUE THREAD

**Issue by scqsu** [AmazingAng/WTFSolidity#218]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/10421790/191672316-2030e38e-2fe7-434e-b33a-b6a44155f4fe.png">

**Comment by AmazingAng** [comment]
感谢提醒，上面的合约忘记删了，现在改正过来了。
