### ISSUE TITLE
11讲 【插入排序合约】的跳转链接失效

### ISSUE THREAD

**Issue by jujube109** [AmazingAng/WTFSolidity#55]
插入排序合约的跳转地址不是最新的第七讲的插入合约url
![image](https://user-images.githubusercontent.com/50389632/170931606-0cc48257-a366-4f46-986b-c1e6b7c6fa7a.png)
![image](https://user-images.githubusercontent.com/50389632/170931696-f73dd2ab-1247-45d9-b74b-1d3109ca6055.png)

**Comment by AmazingAng** [comment]
我在github上改正了，mirror上的文章会在审核结束后更新。感谢！
