### ISSUE TITLE
第六讲 小错误

### ISSUE THREAD

**Issue by JustinAsdz** [AmazingAng/WTFSolidity#7]
规则4:
其中是_**VAR**_映射变量名

**Comment by AmazingAng** [comment]
感谢 已改正！ (https://github.com/AmazingAng/WTFSolidity/commit/0370164091e11cbd3564c6d78892667b6ccfc702)
请你留下你的钱包地址，以后会发POAP

**Comment by JustinAsdz** [comment]
> 感谢 已改正！ ([0370164](https://github.com/AmazingAng/WTFSolidity/commit/0370164091e11cbd3564c6d78892667b6ccfc702)) 请你留下你的钱包地址，以后会发POAP

just found,my address is :
0x3Da4da2De7a937aEbBe26166B4f06EDE7Bc77BE5
