### ISSUE TITLE
Solidity极简入门: 24. Create2 章节中歧义

### ISSUE THREAD

**Issue by sdfgsdfsdf** [AmazingAng/WTFSolidity#85]
原文：
工厂合约（PairFactory2）有两个状态变量getPair是两个代币地址到币对地址的map，方便根据代币找到币对地址；allPairs是币对地址的数组，**存储了所有代币地址**。

最后一句应该改为：储存了所有币对地址

**Comment by AmazingAng** [comment]
已更正
