### ISSUE TITLE
关于Solidity版本差异产生的一些困惑

### ISSUE THREAD

**Issue by Eanam** [AmazingAng/WTFSolidity#9]
问题：【合约安全第一讲】第5点关于Fallback的用法

> fallback function不仅在普通以太传输（没有msg.data）时调用....

与【入门第十六讲】receive和fallback的区别产生的一点小困惑

> msg.data不为空或不存在receive时，会触发fallback()....

经过 @AmazingAng 的解答，知道是Solidity 0.5.0时还没有receive函数且fallback函数当时也直接声明为function()。
因此对这份新手教程有个小建议。

建议：
1. 作为现阶段的入门文章，考虑大部分是新手的情况，大家基本都是从0.8.4版本开始学习这门语言。因此，如果在讲解一些经典案例或者经典合约时，希望可以标注下案例和合约中Solidity与当下学习的版本的一些差异性。
2. 也可以将Solidity几个重要版本更新的差异点作为一篇单独的文章，也可以带领大家理解这些升级背后的深层考虑（我愿意在对Solidity有更好掌握之后，对此文章献出绵薄之力）

**Comment by AmazingAng** [comment]
感谢 @Eanam 的建议，我已经在【合约安全第一讲】相应地方注明了 solidity 0.5.0版本和0.8.4版本的差异。
也期待你在掌握solidity，一起写一篇版本差异的文章。
